config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions, only: [:index, :new, :create]
  resources :users, only: [:new, :create]
  get '/users', to: 'users#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post 'correct/:question_id', to: 'question_operations#correct'
  post 'wrong/:question_id', to: 'question_operations#wrong'
  post 'importance_change/:question_id', to: 'question_operations#importance_change'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :que_cate_relations, dependent: :destory
  has_many :questions, through: :que_cate_relations
end

app/models/que_cate_relation.rb
class QueCateRelation < ApplicationRecord
  belongs_to :category
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence:true, length: {maximum: 50}
  validates :question, presence:true, length: {maximum: 500}
  validates :answer, presence:true, length: {maximum: 500}

  belongs_to :user

  scope :recent, -> { order(created_at: "DESC") }
  scope :remaining_time_asc, -> { order(next_ans_date: "ASC")}
  scope :importance_desc, -> { order(importance: "DESC") }
  scope :should_ans_order, ->{ remaining_time_asc.importance_desc }

  def created_time
    (created_at + 9.hour).strftime("%Y/%m/%d %H:%M:%S")
  end

  def last_ans_time
    (last_ans_date + 9.hour).strftime("%Y/%m/%d %H:%M:%S")
  end

  def ans_count
    all_cnt = correct_cnt + wrong_cnt
    if all_cnt == 0
      "未回答"
    else
      correct_cnt.to_s + " / " + all_cnt.to_s
    end
  end

  def time_to_ans
    remaining_time = (self&.last_ans_date - Time.now).to_i
    case importance
    when 0 # +6ヶ月
      remaining_time += 6*30*24*60*60
    when 1 # +3ヶ月
      remaining_time += 3*30*24*60*60
    when 2 # +1ヶ月
      remaining_time += 1*30*24*60*60
    when 3 # +7日
      remaining_time += 7*24*60*60
    when 4 # +3日
      remaining_time += 3*24*60*60
    when 5 # 12時間後
      remaining_time += 12*60*60
    end
    sec = remaining_time + 60 #表示上60秒微調整
    min = sec/60%60
    hour = sec/3600%24
    day = sec/3600/24
    "次の解答まで、あと#{day.to_s}日#{hour.to_s}時間#{min.to_s}分"
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: { message: "名前は必須です"}, length: {maximum: 12, message: "名前は12文字以内でお願いします"}
  validates :email,
   uniqueness:{ message: "メールアドレスが間違えているか、既に登録されています"},
   format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message:"メールアドレスが間違えているか、既に登録されています"},allow_blank: true
  validates :email,presence: { message: "メールアドレスは必須です"}
  validates :password, presence: true, length: { minimum: 6, message: "パスワードは6文字以上でお願いします" }
  has_secure_password
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/question_operations_controller.rb
class QuestionOperationsController < ApplicationController
  before_action :question_set

  def correct
    importance = @question.importance
    correct_cnt = @question.correct_cnt + 1
    importance -= 1 if importance > 0
    @question.update(importance: importance , correct_cnt: correct_cnt, last_ans_date: Time.now, next_ans_date: next_ans_date(importance))
  end

  def wrong
    importance = @question.importance
    wrong_cnt = @question.wrong_cnt + 1
    importance += 1 if importance < 5
    @question.update(importance: importance , wrong_cnt: wrong_cnt, last_ans_date: Time.now, next_ans_date: next_ans_date(importance))
  end

  def importance_change
    importance = params[:importance]
    @question.update(importance: importance, last_ans_date: Time.now, next_ans_date: next_ans_date(importance))
  end

  private

  def question_set
    @question = Question.find(params[:question_id])
  end

  def next_ans_date(importance)
    case importance
    when 0
      Time.now + 6.months
    when 1
      Time.now + 3.months
    when 2
      Time.now + 1.month
    when 3
      Time.now + 7.days
    when 4
      Time.now + 3.days
    when 5
      Time.now + 12.hours
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_questions, only: %i[index]


  def index
  end

  def new
    @question = Question.new
    @questions = current_user.questions.recent
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to new_question_path,  notice: "問題を登録しました。"
    else
      flash.now[:notice] = "問題が発生しました。"
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :question, :answer).merge(user_id: current_user.id, last_ans_date: Time.now)
  end

  def set_questions
    @questions = current_user.questions.should_ans_order
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "こんにちは#{user.name}さん"
    else
      flash.now[:notice] =  "メールアドレスまたはパスワードが違います。"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "#{@user.name}さん、ようこそ！"
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_operations_helper.rb
module QuestionOperationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SuperMemoryApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .all-container
      -if flash.notice.present?
        .alert.alert-success= flash.notice
    = yield

app/views/questions/_question.html.haml
.question-wrap{ id: "question-wrap-#{question.id}" }
  .created-time
    =question.created_time
  .question-box
    .question-box__title
      =question.title
    .question-box__set
      .question-box__set__question
        =question.question
      .question-box__set__answer.opacity-zero{id: "question_ans_#{question.id}"}
        =question.answer
  .question-operation
    .ans_show_btn_contents{ id: "before_show_#{question.id}" }
      .correct_ans_cnt
        ="正解数：#{question.ans_count}"
      %button.ans_show_btn.btn-success{ question_id: "#{question.id}" } 解答を見る
    .ans_show_btn_contents.display-none{ id: "after_show_#{question.id}" }
      =button_to "わからなかった。", "/wrong/#{question.id}", {method: :post, class: "btn-danger ans_check_btn", id: "wrong-btn-#{question.id}" ,question_id: "#{question.id}"}
      =button_to "わかった。", "/correct/#{question.id}", {method: :post, class: "btn-primary ans_check_btn", id: "correct-btn-#{question.id}" ,question_id: "#{question.id}"}
      =form_with url:"/importance_change/#{question.id}", local:true do |f|
        =f.label :importance,"次までの解答時間を選ぶ", class: "form-importance"
        =f.select :importance, [['6ヶ月後', 0],['3ヶ月後', 1],['1ヶ月後', 2],['7日後', 3],['3日後', 4],['12時間後', 5]], { include_blank: true, selected: question.importance }, { id: "importance", class: "aaa" }
        =f.submit "更新", class: 'btn btn-success ans_check_btn', id:"correct-btn-#{question.id}" ,question_id: "#{question.id}"
    .ans_show_btn_contents.display-none{ id: "after_ans_#{question.id }" }
      .correct_ans_cnt
        =question.time_to_ans
      %button.release_btn.btn-danger{ question_id: "#{question.id}" } リリース

app/views/questions/index.html.haml
=render partial: 'shared/header', locals: {page_title: ""}
.middle
  =render partial: 'shared/side_bar', locals: {page_title: "My page"}
  .container
    = render @questions

app/views/questions/new.html.haml
=render partial: 'shared/header', locals: {page_title: ""}
.middle
  =render partial: 'shared/side_bar', locals: {page_title: "New"}
  .container
    - if @question.errors.present?
      %ul.error_explanation
        - @question.errors.full_messages.each do |message|
          %li= message
    .form-question-new
      =form_with model: @question, local: true do |f|
        .form-group.form-group-title
          = f.label :title, "タイトル" ,class: "label label-title"
          = f.text_field :title, class: "form form-title", autocomplete:'off'
          .form-caution (最大50文字)
        .form-group-set
          .form-group.form-group-set__form
            = f.label :question, "問題" ,class: "label label-question"
            = f.text_area :question, class: "form-group__form form-question", autocomplete:'off'
            .form-group__caution (最大400文字)
          .form-group.form-group-set__form
            = f.label :answer, "答え" , class: "label label-answer"
            = f.text_area :answer, class: "form form-group__form form-answer", autocomplete:'off'
            .form-group__caution (最大400文字)
        .form-group.form-group-category#category_forms
          = f.label :category, "カテゴリ",class: "label label-category"
          = f.hidden_field :category, class: "form-group__form form-category",value:"hidden_cate"
        .category-add-forms
          .category-add-forms__set
            = text_field_tag :categories, "",{id:"cate-1_input",cate_id:1}
            %button{type:"button",class:"cate_btn btn-primary",id:"cate-1_btn", category_id:1} 確定
        =f.submit "登録", class: 'btn btn-primary form-btn'
    .question-new-questions
      = render @questions


-# <input type="text" name="category" id="cate-1_input" value="" cate_id="1">

-# <input class="cate_btn" id="cate-1_btn" cate_id="1" type="submit" value="確定">

-# <input class="form-group__form form-category" value="hidden_cate" type="hidden" name="question[category-1]" id="question_category">

app/views/shared/_header.html.haml
.header
  %h1.header__title
    =link_to "MemoryApp", root_path, class:"header__title"
  %h1.header__title
    =page_title
  %ul.header__menu__list
    -if current_user
      %li.header__menu__list-login
      =link_to "ログアウト", logout_path, method: :delete ,class: "header__menu-login"
    -else
      %li.header__menu__list-login
        =link_to "ログイン", login_path ,class: "header__menu-login"
      %li.header__menu__list-login
        =link_to "新規会員登録", new_user_path ,class: "header__menu-login"

app/views/shared/_side_bar.html.haml
.side_bar
  %h1.page_title=page_title
  = button_to "知識の登録へ", {controller: 'questions', action: 'new'}, {method: :get , class: "question-new-btn"}

app/views/users/new.html.haml
=render partial: 'shared/header', locals: {page_title: ""}
.middle
  .container
    .login-form-groups
      = form_with model: @user, local: true do |f|
        -@user.errors.messages[:name].each do |message|
          .form_error_message=message
        .form-group
          = f.label :name, '名前'
          = f.text_field :name, class: 'form-control login-form', autocomplete:'off'
        -@user.errors.messages[:email].each do |message|
          .form_error_message=message
        .form-group
          = f.label :email, 'メールアドレス'
          = f.text_field :email, class: 'form-control login-form', autocomplete:'off'
        -if @user.errors.messages[:password] != []
          .form_error_message パスワードを正しく登録してください。
        .form-group
          = f.label :password, 'パスワード'
          = f.password_field :password, class: 'form-control login-form', autocomplete:'off'
        .form-group
          = f.label :password_confirmation, 'パスワード (確認)'
          = f.password_field :password_confirmation, class: 'form-control login-form', autocomplete:'off'
        = f.submit '登録', class: 'btn btn-primary login-btn'